services:
    _defaults:
        autowire: true
        public: false

    LoremIpsum\ActionLoggerBundle\Model\ActionLoggerInterface: '@LoremIpsum\ActionLoggerBundle\Utils\ActionLogger'

    LoremIpsum\ActionLoggerBundle\Utils\ActionLogger:
        class: LoremIpsum\ActionLoggerBundle\Utils\ActionLogger

    LoremIpsum\ActionLoggerBundle\Twig\LogActionExtension:
        class: LoremIpsum\ActionLoggerBundle\Twig\LogActionExtension
        tags: ['twig.extension']

    LoremIpsum\ActionLoggerBundle\Factory\ActionFactory:
        class: LoremIpsum\ActionLoggerBundle\Factory\ActionFactory
        arguments: ['@doctrine.orm.entity_manager', '%loremipsum.action_logger.mapping%', '%loremipsum.action_logger.entity_mapping%']

    LoremIpsum\ActionLoggerBundle\Repository\LogActionRepository:
        class: LoremIpsum\ActionLoggerBundle\Repository\LogActionRepository
        tags: ['doctrine.repository_service']